### PR TITLE
V1.718 Update RepoLoadExec CLI and RepoLoadWorkflow to support CLI usage from weekly-update workflow

### PR DESCRIPTION
**Pull request by piehld**
Jira Ticket: [RO-4234](https://rcsbpdb.atlassian.net/browse/RO-4234)

Migrated the following ExDB tasks to using CLI-based execution:

- `etl.load_ex.CoreCacheDataBuilding`
- `etl.load_ex.BirdChemCompCoreDataLoading`
- `etl.load_ex.CoreDataDbWiping`
- `etl.load_ex.CoreDataListSplitting`
- `etl.load_ex.CoreDataLoading`
- `etl.load_ex.CoreDataLoadingOneTask`
- `etl.load_ex.CompModelCoreDataDbWiping`
- `etl.load_ex.CompModelCoreDataListSplitting`
- `etl.load_ex.CompModelCoreDataLoading`
- `etl.load_ex.CompModelCoreDataLoadingOneTask`
- `etl.load_ex.EtlSeqClustersDataLoading`
- `etl.load_ex.EtlRepoHoldingsDataLoading`

PR to be merged in parallel with: https://github.com/rcsb/weekly-update-workflow/pull/348

### CODE REVIEW

**Comment by brindakv** [comment]
Thanks @piehld. I have a couple of general questions. 
1. Is incremental update supported? 
2. Do the tests in the `rcsb/db/tests*` directory work?

**Comment by piehld** [comment]
@brindakv, yes and yes.

Incremental update is actually the default. And here is the latest Azure build: https://dev.azure.com/rcsb/RCSB%20PDB%20Python%20Projects/_build/results?buildId=8599&view=results

**Comment by piehld** [comment]
@brindakv Yes tests are run during the Azure build, though not all of them are run due to the use of `@unittest.skip` in cases of large tests or other historical reasons. Also, it doesn't look like `tests-validate` has been included in the tox tests (see [tox.ini](https://github.com/rcsb/py-rcsb_db/blob/master/tox.ini#L15-L27)). 

You can view which tests actually ran and their output here (which you can navigate to via the link I sent earlier, too): https://dev.azure.com/rcsb/RCSB%20PDB%20Python%20Projects/_build/results?buildId=8599&view=logs&j=ca5428db-fcca-57fe-9a54-42b1eb1d9883&t=f20abe10-5107-5d1a-d791-f5b775acf553

> The one I use frequently and tested locally (tests-validate/testSchemaDataPrepValidatePDB.py) is failing

I don't see that file in the repository...do you mean `tests-validate/testSchemaDataPrepValidate.py`?

If we want to start including those other tests, that would be a separate effort to do. FWIW, I didn't modify anything that would affect how data is loaded, so I don't think these changes would have impacted the validation tests.

**Comment by brindakv** [comment]
> I don't see that file in the repository...do you mean tests-validate/testSchemaDataPrepValidate.py?

Yes. That is the one that is not working. Sorry for the typo.

**Comment by brindakv** [comment]
@piehld The tests don't work with the code in the master branch either. I'll create a new issue to address it.

**Comment by piehld** [comment]
Thanks for checking @brindakv and creating the issue. If you're able to provide additional details on which particular test you're running and your setup, that would be helpful too. But no rush.

I'll go ahead and merge this now though.

**Pull request merged**
