### PR TITLE
RO-2981: future-proof parsing of cluster data

### PR DESCRIPTION
**Pull request by JonStargaryen**
Only split at last `_` when handling sequence cluster data.

### CODE REVIEW

**Comment by piehld** [comment]
Hi @JonStargaryen , sorry for the delay. Can you please create this PR into [staging-to-master](https://github.com/rcsb/py-rcsb_db/tree/staging-to-master)? That's what Brinda and I are using for development purposes.

**Comment by piehld** [comment]
Great thanks! Looks good to me.

**Review by piehld — APPROVED** [review]

**Comment by piehld** [comment]
@brindakv FYI

**Comment by brindakv** [comment]
Thanks @piehld 
@JonStargaryen looks good to me.

**Comment by josemduarte** [comment]
@piehld is this change now released in pypi? It'd be really handy to have to continue testing the whole weekly update pipeline

**Comment by piehld** [comment]
No not yet. @brindakv and I have been preparing all computed-model specific updates in the staging-into-master branch. We have yet to test whether the updates we've added will be backwards compatible with the existing schemas in production (currently, the code has been written to accommodate the new unified schema)...so we would need to do that prior to pushing this updated py-rcsb_db code into a new PyPI version.

**Comment by josemduarte** [comment]
Ok thanks, understood. Then I'll use the staging-into-master branch.

**Comment by josemduarte** [comment]
@piehld would it be possible by any chance to cherry-pick this into the prod branch? It would make testing much easier.

**Comment by piehld** [comment]
Sorry for the delay @josemduarte. @brindakv and I would like to actually merge this branch into production anyway, but will require testing the workflow with current production schemas. That said, if you'd like it before Monday, I could cherry-pick this commit into the other [PR I created](https://github.com/rcsb/py-rcsb_db/pull/49#pullrequestreview-995622630), and then merge that (though, again that should ideally be tested first). So, I can try to test this branch with the production schemas for the weekend, and if the experimental models look good, we can merge this entire branch into master.

**Comment by josemduarte** [comment]
@piehld would you know what would be the version corresponding to latest master? I ran the EtlDataLoading task on a newly created instance before yesterday and it still tripped in parsing the identifiers correctly (the fix in this PR). 

This is what pip says about installed versions, do they look correct to you?

```
pip3 freeze | grep rcsb
rcsb.db==1.698
rcsb.exdb==0.92
rcsb.utils.chem==0.76
rcsb.utils.chemref==0.82
rcsb.utils.citation==0.19
rcsb.utils.config==0.37
rcsb.utils.dictionary==0.85
rcsb.utils.ec==0.23
rcsb.utils.go==0.17
rcsb.utils.insilico3d==0.28
rcsb.utils.io==1.35
rcsb.utils.multiproc==0.18
rcsb.utils.repository==0.35
rcsb.utils.seq==0.65
rcsb.utils.seqalign==0.25
rcsb.utils.struct==0.42
rcsb.utils.targets==0.59
rcsb.utils.taxonomy==0.40
rcsb.utils.validation==0.28
rcsb.workflow==0.32
```

**Comment by josemduarte** [comment]
Thanks @piehld . There's something odd, I've just created a new instance that installed everything from scratch and I'm still getting `rcsb.db==1.698`. I'll do some more digging.

**Pull request merged**
